import "./globals.css";
import { Kumbh_Sans } from "next/font/google";

import Header from "@/components/header";
import Footer from "@/components/footer";

const kumbhSans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Mentor | E-commerce product page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>
        <div className="container">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
